### PR TITLE
fix: added logic that removes ds from collection on remove

### LINKED ISSUE #462: Dataset delete doesn't immediately update the collection
After you remove a dataset - you can still see the deleted dataset and the dataset count will not change until you restart the page

### PR DESCRIPTION
**Pull request by boandriy**
added logic that removes ds from collection on remove

fixes #462

### CODE REVIEW

**Review by chriswhong — CHANGES_REQUESTED** [review]
Maybe I am missing something, but I ran this locally and removing from collection view didn't update the list (the deleted dataset was still present in the list)

**Comment by boandriy** [comment]
@chriswhong , added animation for remove

**Review by chriswhong — APPROVED** [review]
The animation looks great! All good from the product side.

**Review by ramfox — APPROVED** [review]
LGTM

**Pull request merged**
