### PR TITLE
feat: extending e2e tests to clean after themselves

### LINKED ISSUE #319: e2e tests should clean up after themselves, removing datasets and deleting test user
If I understand this correctly, bugs in cloud/backend prevent our current test suite from cleaning up after itself. Let's solve those issues & then update tests so we're ending back in a clean state. e2e tests should still use `test_` username / dataset prefixes for easier identification.

### Steps to Complete
* [ ] Identify issues preventing e2e tests from doing a "clean" setup where no "special" usernames are required, and any issues preventing workflow, dataset, and user deletion. Link those issues here.
* [ ] Fix those issues
* [ ] Update e2e tests
* [ ] party

### PR DESCRIPTION
**Pull request by boandriy**
extending e2e tests to clean after themselves deleting the created datasets

closes #319

### CODE REVIEW

**Comment by ramfox** [comment]
cool, the dataset clean up looks good!

I just have questions about the username/password & creating a new account.

Is there a plan for how we are going to get to the point of being able to remove a user all in the e2e tests?

Also, it doesn't look like we use the `USERNAME` or `PASSWORD` global vars any longer, we should remove those & the check to ensure that they are set environment variables.

**Comment by boandriy** [comment]
> cool, the dataset clean up looks good!
> 
> I just have questions about the username/password & creating a new account.
> 
> Is there a plan for how we are going to get to the point of being able to remove a user all in the e2e tests?
> 
> Also, it doesn't look like we use the `USERNAME` or `PASSWORD` global vars any longer, we should remove those & the check to ensure that they are set environment variables.

I talked with @Arqu , about cleaning the users. And we decided that this will be done on the BE, as there are few issues with giving an access to just delete a user. Yep, will clean the Unused global vars.

**Review by ramfox — APPROVED** [review]
fab! LGTM

**Comment by Arqu** [comment]
Yep, the above is correct. User deletion will be done manually every now and then (will make a cron if it becomes tedious) simply based off of the prefix for the user.

**Pull request merged**
