### PR TITLE
fix(auth): update routes for fetching session user profile

### PR DESCRIPTION
**Pull request by Arqu**
Part of https://github.com/qri-io/qri/issues/1806

### CODE REVIEW

**Review by b5 — COMMENTED** [review]
hrm, this seems to change the meaning of this function. I'd say leave this with me @Arqu & I can add a commit that gets this into mergeable shape

**Comment by Arqu** [comment]
Hmmm, so the thing was we didn't have a concept of identity and session on qri core until now. Profile gets us most of the way and it nearly behaves the same now with tokens being used. Only missing piece is that `identity/session` should error if the user is not providing a valid token, this just gives the base profile (which from a usage perspective might not be that wrong?)

**Review by b5 — APPROVED** [review]
looks good to me. Your comment points to a need on the qri core side to sort out what is & isn't "good behavior" now that sessions have been implicitly added.

**Comment by Arqu** [comment]
Made an issue out of it.

**Pull request merged**
